import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const proposalsRepo =
  process.env.PROPOSALS_REPO || "Plebly/proposals";
const proposalsRaw = `https://raw.githubusercontent.com/${proposalsRepo}/main`;

function slugify(label) {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "");
}

function parseParametersMarkdown(md) {
  const params = {};
  for (const line of md.split("\n")) {
    const m = line.match(/^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|/);
    if (!m) continue;
    const key = m[1].trim();
    const value = m[2].trim();
    if (key.startsWith("-") || key === "Parameter" || key === "Role" || key === "Mode") {
      continue;
    }
    const slug = slugify(key);
    if (slug in params) continue;
    params[slug] = value;
  }
  return params;
}

function parseSats(value) {
  const m = value.replace(/,/g, "").match(/(\d+)\s*sats?/i);
  return m ? Number(m[1]) : null;
}

function parsePercent(value) {
  const m = value.match(/([\d.]+)\s*%/);
  return m ? Number(m[1]) : null;
}

async function loadParametersMarkdown() {
  const localPath = join(root, "../proposals/PARAMETERS.md");
  if (process.env.PARAMETERS_PATH && existsSync(process.env.PARAMETERS_PATH)) {
    return readFileSync(process.env.PARAMETERS_PATH, "utf8");
  }
  if (existsSync(localPath)) {
    return readFileSync(localPath, "utf8");
  }
  const res = await fetch(`${proposalsRaw}/PARAMETERS.md`);
  if (!res.ok) {
    throw new Error(
      `Could not fetch PARAMETERS.md (${res.status}). Set PARAMETERS_PATH for offline builds.`,
    );
  }
  return res.text();
}

function substitute(template, params, extras) {
  const all = { ...params, ...extras };
  return template.replace(/\{\{([a-z0-9_]+)\}\}/g, (_, key) => {
    if (all[key] == null) {
      throw new Error(`Missing placeholder {{${key}}} in about template`);
    }
    return all[key];
  });
}

function emitTs(modulePath, body) {
  mkdirSync(dirname(modulePath), { recursive: true });
  writeFileSync(
    modulePath,
    `/* Auto-generated by scripts/build-about.mjs — do not edit */\n${body}\n`,
    "utf8",
  );
}

function splitSections(md) {
  const sections = [];
  for (const chunk of md.split(/^##\s+/m).filter((c) => c.trim())) {
    const nl = chunk.indexOf("\n");
    const title = (nl === -1 ? chunk : chunk.slice(0, nl)).trim();
    const body = (nl === -1 ? "" : chunk.slice(nl + 1)).trim();
    sections.push({ id: slugify(title), title, body });
  }
  return sections;
}

function parseBeliefs(body) {
  const beliefs = [];
  for (const para of body.split(/\n\n+/)) {
    const m = para.trim().match(/^\*\*([^*]+)\.\*\*\s+([\s\S]+)$/);
    if (m) beliefs.push({ title: m[1], body: marked.parseInline(m[2].trim()) });
  }
  return beliefs;
}

function parseSteps(body) {
  const steps = [];
  for (const line of body.split("\n")) {
    const m = line
      .trim()
      .match(/^\d+\.\s+\*\*([^*]+)\*\*\s+[—–-]\s*(.+)$/);
    if (m) steps.push({ title: m[1], body: m[2].trim() });
  }
  return steps;
}

async function main() {
  const parametersMd = await loadParametersMarkdown();
  const params = parseParametersMarkdown(parametersMd);
  const template = readFileSync(join(root, "content/about.md"), "utf8");

  const network = (process.env.VITE_BITCOIN_NETWORK || "signet").toLowerCase();
  const bitcoinNetwork = network === "signet" ? "signet" : "mainnet";
  const aboutMd = substitute(template, params, { bitcoin_network: bitcoinNetwork });

  const aboutHtml = marked.parse(aboutMd, { async: false });
  const sections = splitSections(aboutMd);
  const byId = Object.fromEntries(sections.map((s) => [s.id, s]));
  const intro = byId.about_plebly;
  const beliefs = parseBeliefs(byId.what_we_believe?.body || "");
  const steps = parseSteps(byId.how_it_works?.body || "");
  const genDir = join(root, "src/generated");

  emitTs(
    join(genDir, "about-html.ts"),
    `export const ABOUT_HTML = ${JSON.stringify(aboutHtml)};`,
  );

  emitTs(
    join(genDir, "about-data.ts"),
    `export type AboutBelief = { title: string; body: string };
export type AboutStep = { title: string; body: string };
export type AboutParamDisplay = { label: string; value: string; hint: string };

export const ABOUT_INTRO_HTML = ${JSON.stringify(
      intro ? marked.parse(intro.body, { async: false }) : "",
    )};

export const ABOUT_LIGHTNING_HTML = ${JSON.stringify(
      byId.lightning_donations
        ? marked.parse(byId.lightning_donations.body, { async: false })
        : "",
    )};

export const ABOUT_BUILDERS_HTML = ${JSON.stringify(
      byId.for_builders
        ? marked.parse(byId.for_builders.body, { async: false })
        : "",
    )};

export const ABOUT_BELIEFS: AboutBelief[] = ${JSON.stringify(beliefs, null, 2)};

export const ABOUT_STEPS: AboutStep[] = ${JSON.stringify(steps, null, 2)};

export const ABOUT_PARAM_LABELS: AboutParamDisplay[] = ${JSON.stringify(
      [
        {
          label: "Submission fee",
          value: params.submission_fee,
          hint: "Paid when you open a proposal PR; exact and non-refundable.",
        },
        {
          label: "Platform fee",
          value: params.platform_fee,
          hint: "Deducted only on successful completion.",
        },
        {
          label: "Claim floor",
          value: params.minimum_funding_claim_floor,
          hint: "Minimum escrow balance before a builder can claim.",
        },
        {
          label: "Claim window",
          value: params.claim_window,
          hint: `After claim acceptance, with a possible ${params.claim_extension || "extension"}.`,
        },
        {
          label: "Milestone threshold",
          value: params.milestone_threshold,
          hint: "Milestone splits apply above this amount.",
        },
      ],
      null,
      2,
    )};

export const ABOUT_BITCOIN_NETWORK = ${JSON.stringify(bitcoinNetwork)};`,
  );

  const submissionFeeSats = parseSats(params.submission_fee);
  const claimFloorSats = parseSats(params.minimum_funding_claim_floor);
  const milestoneSats = parseSats(params.milestone_threshold);
  const platformFeePct = parsePercent(params.platform_fee);

  if (
    submissionFeeSats == null ||
    claimFloorSats == null ||
    milestoneSats == null ||
    platformFeePct == null
  ) {
    throw new Error("Failed to parse numeric values from PARAMETERS.md");
  }

  emitTs(
    join(genDir, "parameters.ts"),
    `export const SUBMISSION_FEE_SATS = ${submissionFeeSats};
export const CLAIM_FLOOR_SATS = ${claimFloorSats};
export const MILESTONE_THRESHOLD_SATS = ${milestoneSats};
export const PLATFORM_FEE_PERCENT = ${platformFeePct};`,
  );

  console.log("Generated about page and parameters from PARAMETERS.md");
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
