import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const proposalsRepo =
  process.env.PROPOSALS_REPO || "Plebly/proposals";
const proposalsRaw = `https://raw.githubusercontent.com/${proposalsRepo}/main`;

function slugify(label) {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "");
}

function parseParametersMarkdown(md) {
  const params = {};
  for (const line of md.split("\n")) {
    const m = line.match(/^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|/);
    if (!m) continue;
    const key = m[1].trim();
    const value = m[2].trim();
    if (key.startsWith("-") || key === "Parameter" || key === "Role" || key === "Mode") {
      continue;
    }
    const slug = slugify(key);
    if (slug in params) continue;
    params[slug] = value;
  }
  return params;
}

function parseSats(value) {
  const m = value.replace(/,/g, "").match(/(\d+)\s*sats?/i);
  return m ? Number(m[1]) : null;
}

function parsePercent(value) {
  const m = value.match(/([\d.]+)\s*%/);
  return m ? Number(m[1]) : null;
}

async function loadParametersMarkdown() {
  const localPath = join(root, "../proposals/PARAMETERS.md");
  if (process.env.PARAMETERS_PATH && existsSync(process.env.PARAMETERS_PATH)) {
    return readFileSync(process.env.PARAMETERS_PATH, "utf8");
  }
  if (existsSync(localPath)) {
    return readFileSync(localPath, "utf8");
  }
  const res = await fetch(`${proposalsRaw}/PARAMETERS.md`);
  if (!res.ok) {
    throw new Error(
      `Could not fetch PARAMETERS.md (${res.status}). Set PARAMETERS_PATH for offline builds.`,
    );
  }
  return res.text();
}

function substitute(template, params, extras) {
  const all = { ...params, ...extras };
  return template.replace(/\{\{([a-z0-9_]+)\}\}/g, (_, key) => {
    if (all[key] == null) {
      throw new Error(`Missing placeholder {{${key}}} in about template`);
    }
    return all[key];
  });
}

function emitTs(modulePath, body) {
  mkdirSync(dirname(modulePath), { recursive: true });
  writeFileSync(
    modulePath,
    `/* Auto-generated by scripts/build-about.mjs — do not edit */\n${body}\n`,
    "utf8",
  );
}

async function main() {
  const parametersMd = await loadParametersMarkdown();
  const params = parseParametersMarkdown(parametersMd);
  const template = readFileSync(join(root, "content/about.md"), "utf8");

  const network = (process.env.VITE_BITCOIN_NETWORK || "signet").toLowerCase();
  const aboutMd = substitute(template, params, {
    bitcoin_network: network === "signet" ? "signet" : "mainnet",
  });

  const aboutHtml = marked.parse(aboutMd, { async: false });
  const genDir = join(root, "src/generated");

  emitTs(
    join(genDir, "about-html.ts"),
    `export const ABOUT_HTML = ${JSON.stringify(aboutHtml)};`,
  );

  const submissionFeeSats = parseSats(params.submission_fee);
  const claimFloorSats = parseSats(params.minimum_funding_claim_floor);
  const milestoneSats = parseSats(params.milestone_threshold);
  const platformFeePct = parsePercent(params.platform_fee);

  if (
    submissionFeeSats == null ||
    claimFloorSats == null ||
    milestoneSats == null ||
    platformFeePct == null
  ) {
    throw new Error("Failed to parse numeric values from PARAMETERS.md");
  }

  emitTs(
    join(genDir, "parameters.ts"),
    `export const SUBMISSION_FEE_SATS = ${submissionFeeSats};
export const CLAIM_FLOOR_SATS = ${claimFloorSats};
export const MILESTONE_THRESHOLD_SATS = ${milestoneSats};
export const PLATFORM_FEE_PERCENT = ${platformFeePct};`,
  );

  console.log("Generated about page and parameters from PARAMETERS.md");
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
