/** Max skills/interests tags stored on a profile (matches Worker validation). */
export const MAX_SKILLS_TAGS = 20;

/**
 * Quick-pick chips shown under the skills control.
 * Full vocabulary still powers autocomplete.
 */
export const SKILLS_PRESET_TAGS = [
  "bitcoin-core",
  "lightning",
  "rust",
  "c++",
  "python",
  "typescript",
  "security",
  "cryptography",
  "wallets",
  "docs",
  "research",
  "ui",
] as const;

const SKILLS_VOCABULARY = [
  // Bitcoin protocol & research
  "bitcoin-core",
  "bitcoin",
  "protocol",
  "consensus",
  "p2p",
  "networking",
  "mempool",
  "mining",
  "proof-of-work",
  "script",
  "miniscript",
  "descriptors",
  "psbt",
  "taproot",
  "musig",
  "multisig",
  "timelocks",
  "covenants",
  "soft-forks",
  "bip",
  "policy",
  "knots",
  "fee-estimation",
  "utxo",
  "coin-selection",
  "privacy",
  "cryptography",
  "security",
  "audit",
  "formal-methods",
  "research",
  // Lightning & layers
  "lightning",
  "ldk",
  "lnd",
  "core-lightning",
  "eclair",
  "boltz",
  "submarine-swaps",
  "channel-management",
  "routing",
  "onion-messaging",
  "offers",
  "bolt12",
  "fedimint",
  "ecash",
  "ark",
  "liquid",
  "sidechains",
  "rgb",
  "dlc",
  "statechains",
  // Wallets & keys
  "wallets",
  "hardware-wallets",
  "bdk",
  "electrum",
  "sparrow",
  "seed-signer",
  "key-management",
  "descriptors-wallets",
  "recovery",
  "backup",
  // Nostr & social
  "nostr",
  "nip",
  "relays",
  "zaps",
  // Languages
  "rust",
  "c",
  "c++",
  "python",
  "javascript",
  "typescript",
  "go",
  "java",
  "kotlin",
  "swift",
  "haskell",
  "nix",
  "shell",
  "sql",
  // App / platform
  "ui",
  "ux",
  "design",
  "frontend",
  "backend",
  "fullstack",
  "react",
  "svelte",
  "vue",
  "wasm",
  "qt",
  "gtk",
  "android",
  "ios",
  "desktop",
  "cli",
  "api",
  "rpc",
  "graphql",
  "websockets",
  // Infra & quality
  "devops",
  "sre",
  "ops",
  "linux",
  "docker",
  "kubernetes",
  "ci-cd",
  "testing",
  "qa",
  "fuzzing",
  "benchmarking",
  "observability",
  "performance",
  "distributed-systems",
  "databases",
  // Product & commons
  "product",
  "project-management",
  "community",
  "education",
  "docs",
  "technical-writing",
  "translations",
  "localization",
  "support",
  "open-source",
  "commons",
  "tooling",
  "developer-tools",
  "sdk",
  "libraries",
  // Adjacent domains
  "legal",
  "compliance",
  "economics",
  "game-theory",
  "mechanism-design",
  "data-analysis",
  "machine-learning",
  "graphics",
  "accessibility",
  "mobile",
  "embedded",
  "hardware",
  "fpga",
  "reverse-engineering",
  "threat-modeling",
  "incident-response",
  "governance",
  "fundraising",
  "operations",
] as const;

/** Sorted unique autocomplete vocabulary for skills & interests. */
export const SUGGESTED_SKILLS_TAGS: readonly string[] = [
  ...new Set(SKILLS_VOCABULARY.map((tag) => tag.toLowerCase())),
].sort((a, b) => a.localeCompare(b));
